runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static/
  static_dir: static
  secure: always

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /.*
  script: blog.py
  secure: always
